# Selenium Configuration
selenium:
  browser: chrome # web browser (e.g., chrome, firefox)
  browserSize: maximised

# Users
defaultUser:
    username: default
    password: 1q2w3e
adminUser:
    uname: default
    pass: 1q2w3e

# Rest Assured Configuration
restAssured:
  baseURL: http://localhost:8080 # Base URL for your REST API endpoints
  authentication:
    username: default
    password: 1q2w3e

# Test Environment Configuration
environment:
  envName: QA # Name of the test environment
  appUrl: http://localhost:8080 # URL of the application under test
  loginPage: http://localhost:8080/ui/#login?

# Other Configuration Settings
other_settings:
  timeout: 30 # Default timeout for WebDriver operations
  log_level: INFO # Logging level for your tests (e.g., INFO, DEBUG)

