# Token
token: /uat/sso/oauth/token
# Base URL
baseURI: http://localhost:8080
healthCheck: /health
# User Controller
getAdminUser: /api/v1/user/superadmin
getUser: /api/v1/user
exportAllUsers: /api/v1/user/export?view=csv
