# Selenium Configuration
browser: chrome # web browser (e.g., chrome, firefox)
browserSize: maximized
chromeOptions: "--start-maximized --disable-extensions --disable-popup-blocking"
firefoxOptions: "--start-maximized --disable-extensions --disable-popup-blocking"

# Users
username: default
password: 1q2w3e

# Test Environment Configuration
envName: https://demo.reportportal.io/ui # Name of the test environment
loginPage: https://demo.reportportal.io/ui/#login
settingsPage: https://demo.reportportal.io/ui/#default_personal/settings/general
dashboardPage: https://demo.reportportal.io/ui/#default_personal/dashboard

# Other Configuration Settings
other_settings:
  timeout: 30 # Default timeout for WebDriver operations
  log_level: INFO # Logging level for your tests (e.g., INFO, DEBUG)

# Test  Configuration
mainPage: https://www.epam.com